version: '3.1'

services:
  db:
    image: mysql:8.3.0
    container_name: cookbooks
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cookbooks
      TZ: "Asia/Tokyo"
